package com.example.journeysapp.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.colorResource
import com.example.journeysapp.R

// Light colors
val primaryLight = Color(0xFF9B3F14)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFBB572A)
val onPrimaryContainerLight = Color(0xFFFFFBFF)
val secondaryLight = Color(0xFF84523D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFDBAA0)
val onSecondaryContainerLight = Color(0xFF794834)
val tertiaryLight = Color(0xFF636100)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB2B029)
val onTertiaryContainerLight = Color(0xFF424100)
val errorLight: Color
    @Composable
    get() = colorResource(R.color.color_error)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF231915)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF231915)
val surfaceVariantLight = Color(0xFFFADCD2)
val onSurfaceVariantLight = Color(0xFF56423B)
val outlineLight = Color(0xFF897269)
val outlineVariantLight = Color(0xFFDDC1B6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392E2A)
val inverseOnSurfaceLight = Color(0xFFFFEDE7)
val inversePrimaryLight = Color(0xFFFFB598)
val surfaceDimLight = Color(0xFFE9D6CF)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EC)
val surfaceContainerLight = Color(0xFFFEEAE3)
val surfaceContainerHighLight = Color(0xFFF8E4DD)
val surfaceContainerHighestLight = Color(0xFFF2DED8)

// Dark colors
val primaryDark = Color(0xFFFFB598)
val onPrimaryDark = Color(0xFF591C00)
val primaryContainerDark = Color(0xFFDF7243)
val onPrimaryContainerDark = Color(0xFF4D1700)
val secondaryDark = Color(0xFFFAB79D)
val onSecondaryDark = Color(0xFF4E2514)
val secondaryContainerDark = Color(0xFF6B3D2A)
val onSecondaryContainerDark = Color(0xFFEAA990)
val tertiaryDark = Color(0xFFCECC44)
val onTertiaryDark = Color(0xFF333200)
val tertiaryContainerDark = Color(0xFFB2B029)
val onTertiaryContainerDark = Color(0xFF424100)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1B110E)
val onBackgroundDark = Color(0xFFF2DED8)
val surfaceDark = Color(0xFF1B110E)
val onSurfaceDark = Color(0xFFF2DED8)
val surfaceVariantDark = Color(0xFF56423B)
val onSurfaceVariantDark = Color(0xFFDDC1B6)
val outlineDark = Color(0xFFA48B82)
val outlineVariantDark = Color(0xFF56423B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF2DED8)
val inverseOnSurfaceDark = Color(0xFF392E2A)
val inversePrimaryDark = Color(0xFF9F4216)
val surfaceDimDark = Color(0xFF1B110E)
val surfaceBrightDark = Color(0xFF433732)
val surfaceContainerLowestDark = Color(0xFF150C09)
val surfaceContainerLowDark = Color(0xFF231915)
val surfaceContainerDark = Color(0xFF281D19)
val surfaceContainerHighDark = Color(0xFF332823)
val surfaceContainerHighestDark = Color(0xFF3E322E)
